[build]
  publish = "dist"
  command = "gridsome build"

[[plugins]]
  package = "netlify-plugin-algolia-export"

[[plugins]]
  package = "netlify-plugin-gridsome-cache"

[[redirects]]
  from = "/resource/*/*"
  to = "/brain/*/*"

[[redirects]]
  from = "/writings/*"
  to = "/*"

[[redirects]]
  from = "writings/dj-get-context"
  to = "/django-get-context-data"