[build]
  publish = "dist"
  command = "gridsome build"

[[plugins]]
  package = "netlify-plugin-algolia-export"

[[plugins]]
  package = "netlify-plugin-gridsome-cache"

[[redirects]]
  from = "/writings/joplin"
  to = "/joplin"

[[redirects]]
  from = "writings/dealing-with-mild-depression"
  to = "/dealing-with-mild-depression"

[[redirects]]
  from = "writings/designing-first-site"
  to = "/designing-first-site"

[[redirects]]
  from = "writings/dj-get-context"
  to = "/django-get-context-data"